### ISSUE TITLE
Missing config files

### ISSUE THREAD

**Issue by Floyer007** [fpiesche/docker-sftp-server#17]
Hi,
the docker container doesn't start out of the box.

The log output looked as followed:
```
sftp-server  | Launching sshd
sftp-server  | /etc/ssh/sshd_config: No such file or directory
```

After copying the _sshd_config_ file manually into my config volume, it worked, but the next error occurred:

`sftp-server  | Error checking authentication key CENSORED in revoked keys file /etc/ssh/revoked_keys: No such file or directory`

So I created _revoked_keys_ as well.

My docker-compose file looks as followed:
```
version: '2'

services:
  sftp-server:
    image: florianpiesche/sftp-server
    container_name: sftp-server
    ports:
      - "2221:22"
    volumes:
      - ./config:/etc/ssh/
      - ./init:/etc/sftp.d/
      - ./authorized-keys:/authorized_keys/
    restart: always
```

The file structure as followed:
```
├── authorized-keys
│   └── user.pub
├── config
│   ├── revoked_keys
│   ├── sshd_config
│   ├── ssh_host_ed25519_key
│   ├── ssh_host_ed25519_key.pub
│   ├── ssh_host_rsa_key
│   └── ssh_host_rsa_key.pub
├── docker-compose.yml
└── init
```

**Comment by fpiesche** [comment]
Ta for pointing this out - I'm testing this in my local sftp server setup where I've got the configuration all set up of course so I hadn't spotted this. Will sort as soon as I have some time...

**Comment by fpiesche** [comment]
This should be fixed in v2022.08.04 :)

**Comment by Floyer007** [comment]
Thank you for looking into this.

Sadly I still get the error.
`sftp-server  | /etc/ssh/sshd_config: No such file or directory`

My image is updated:
```
docker image inspect f7b41689d210 | grep 2022.08
"Created": "2022-08-04T17:38:16.12864479Z",
```
